export const articleData = [
      {
            id: 1,
            title: 'this article title should have not more than 10 words ',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/download.jpeg',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 2,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Alumni Connect',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Campus Life',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Alumni Connect',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Alumni Connect',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },

      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 1,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      }
]