export const articleData = [
      {
            id: 1,
            title: 'this article title should have not more than 10 words ',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/download.jpeg',
            author: 'asdfghasdfghjk',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 2,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Alumni Connect',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 3,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Campus Life',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 4,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Alumni Connect',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 5,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 500,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 6,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 7,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Alumni Connect',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 8,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 9,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 10,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 11,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 12,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 13,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 14,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 15,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 16,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 17,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },

      {
            id: 18,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 19,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 20,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      },
      {
            id: 21,
            title: 'this article title should have not more than 10 words',
            imgMainURL: '/Carouselimages/sample.jpg',
            imgSmURL: '/articleImages/sampleMini.png',
            author: 'asdfgh',
            uploadedBy: 'asdferdfv',
            likes: 125,
            Category: 'Academics',
            date: '12/05/2021',
            feedback: 'asdfghsxcynskjhgfsjgbncjhbknbjhgbjfjh'
      }
]